package markdown

import "fmt"

// FetchDocument fetches a document given an auth mode and a document ID.
// This is a stub implementation returning a small sample Document. The
// real implementation will call Google APIs and map the response into the
// Document model.
func FetchDocument(authMode, docID string) (*Document, error) {
    if docID == "" {
        return nil, fmt.Errorf("missing doc id")
    }
    // Sample document for early feature development and tests.
    return &Document{
        Title: "Sample Doc",
        Body: []Element{
            Heading{Level: 1, Text: "Introduction"},
            Paragraph{Text: "This is a sample document generated by the adapter stub."},
            CodeBlock{Language: "", Code: "echo hello"},
        },
    }, nil
}
