package markdown

import "fmt"

// FetchDocument fetches a document given an auth mode and a document ID.
// This is a stub implementation returning a small sample Document. The
// real implementation will call Google APIs and map the response into the
// Document model.
func FetchDocument(authMode, docID string) (*Document, error) {
	if docID == "" {
		return nil, fmt.Errorf("missing doc id")
	}
	// Sample document for early feature development and tests.
	return &Document{
		Title: "Sample Doc",
		Body: []Element{
			Heading{Level: 1, Text: "Introduction"},
			Paragraph{Text: "This is a sample document generated by the adapter stub."},
			CodeBlock{Language: "", Code: "echo hello"},
		},
	}, nil
}

// DocumentSummary is a lightweight descriptor returned by list operations.
type DocumentSummary struct {
	ID    string
	Title string
}

// ListDocuments returns a sample list of documents. In the real adapter this
// will call the Google Drive/Docs API to list accessible documents.
func ListDocuments(authMode string) ([]DocumentSummary, error) {
	// Return a small static set for early development and tests.
	return []DocumentSummary{
		{ID: "doc-1", Title: "Sample Doc"},
		{ID: "doc-2", Title: "Another Doc"},
	}, nil
}
