package markdown

import (
	"context"
	"fmt"
)

// Tab is one Google Doc tab, possibly with nested child tabs.
type Tab struct {
	ID       string
	Title    string
	Document *Document
	Children []*Tab
}

// FetchedDocument is the result of a Docs get, including the tab tree.
type FetchedDocument struct {
	ID       string
	Title    string
	Tabs     []*Tab
	Document *Document
}

// TabCount returns the number of tabs in the tree (all depths).
func (f *FetchedDocument) TabCount() int {
	if f == nil {
		return 0
	}
	n := countTabs(f.Tabs)
	if n == 0 && f.Document != nil {
		return 1
	}
	return n
}

// IsTabbed reports whether export/preview must refuse this document.
// True when there is more than one tab at any depth, or any childTabs.
func (f *FetchedDocument) IsTabbed() bool {
	if f == nil {
		return false
	}
	if countTabs(f.Tabs) > 1 {
		return true
	}
	return hasChildTabs(f.Tabs)
}

func countTabs(tabs []*Tab) int {
	n := 0
	for _, t := range tabs {
		if t == nil {
			continue
		}
		n++
		n += countTabs(t.Children)
	}
	return n
}

func hasChildTabs(tabs []*Tab) bool {
	for _, t := range tabs {
		if t == nil {
			continue
		}
		if len(t.Children) > 0 {
			return true
		}
		if hasChildTabs(t.Children) {
			return true
		}
	}
	return false
}

// Fetcher loads a document (and tab tree) without the CLI talking to Google directly.
type Fetcher interface {
	Fetch(ctx context.Context, authMode, docID string) (*FetchedDocument, error)
}

// FakeFetcher returns a fixed document or error. Used by unit tests.
type FakeFetcher struct {
	Doc *FetchedDocument
	Err error
}

func (f FakeFetcher) Fetch(ctx context.Context, authMode, docID string) (*FetchedDocument, error) {
	if f.Err != nil {
		return nil, f.Err
	}
	if f.Doc == nil {
		return nil, fmt.Errorf("missing doc id")
	}
	return f.Doc, nil
}

func sampleDocument() *Document {
	return &Document{
		Title: "Sample Doc",
		Body: []Element{
			Heading{Level: 1, Text: "Introduction"},
			Paragraph{Text: "This is a sample document generated by the adapter stub."},
			CodeBlock{Language: "", Code: "echo hello"},
		},
	}
}

// SampleFetcher returns the in-memory sample document (single leaf tab).
type SampleFetcher struct{}

func (SampleFetcher) Fetch(ctx context.Context, authMode, docID string) (*FetchedDocument, error) {
	if docID == "" {
		return nil, fmt.Errorf("missing doc id")
	}
	d := sampleDocument()
	d.DocID = docID
	tab := &Tab{ID: "t0", Title: d.Title, Document: d}
	return &FetchedDocument{
		ID:       docID,
		Title:    d.Title,
		Tabs:     []*Tab{tab},
		Document: d,
	}, nil
}
